### ISSUE TITLE
Inconsistent handling of empty interations by stan_glm.fit and model.matrix.stanreg

### ISSUE THREAD

**Issue by flynngo** [stan-dev/rstanarm#425]
#### Summary:
`stan_glm.fit` drops columns with empty interactions from the data, while `model.matrix` keeps them. Which leads to  `Error in stanmat[, beta_sel, drop = FALSE] : subscript out of bounds`
errors when running `posterior_predict` or `loo`.
#### Description:
`stan_glm.fit` runs the function `center_x`, which drops columns with empty interactions from the data. This is inconsistent with behavior of `model.matrix.default`, which keeps them as a column of zeroes and `glm` which keeps the empty interaction column and assigns a coefficient NA.

This leads to  `Error in stanmat[, beta_sel, drop = FALSE] : subscript out of bounds` when running `posterior_predict` or `loo` and I assume any other function that runs `get_x.default` since that is the function that calls the `model.matrix.default`.

Related to #260 

#### Reproducible Steps:
```{r}
d_empty <- data.frame(y = factor(c(1, 1, 1, 2, 2, 2)),
                      x = factor(c(1, 1, 2, 2, 3, 3)),
                      z = factor(c(1, 2, 1, 2, 1, 1)))

model.matrix(y~x*z, data=d_empty) # We see the column `x3:z2` consists of zeroes

fit <- stan_glm(y~x*z, data = d_empty, family = "binomial")
loo(fit)
# or
posterior_predict(fit)
```

#### RStanARM Version:
2.19.3

#### R Version and Operating System:
Both R version 3.6.2 with MacOS 10.15.3 and 
R version 3.6.0 with CentOS Linux 7 (Core)

#### Hacky fixes
I've managed to address the problem in two ways, but both solutions are hacky and I'm sure will lead to problems that I haven't foreseen.

The first is to add a function

```
drop_empty_levels <- function(x) {
  sel <- apply(x, 2L, function(x) !all(x == 1) && length(unique(x)) < 2)
  if (any(sel)) {
    # drop any column of x with < 2 unique values (empty interaction levels)
    # exception is column of 1s isn't dropped 
    warning("Dropped empty interaction levels: ",
            paste(colnames(x)[sel], collapse = ", "))
    x <- x[, !sel, drop = FALSE]
  }
  return(x)
}
```
and inside `model.matrix.stanreg` replace the line
`NextMethod("model.matrix")` with
`return(drop_empty_levels(model.matrix.default(object)))`.

This creates a different problem in that, if the data the data used to fit the model doesn't contain empty interaction levels, but we call `posterior_predict` with a `newdata` argument that's model.matrix will have empty interaction levels, then these will be dropped and we will still have an inconsistency in the number of columns.

The alternate method is to remove the lines from `center_x` that drop empty interaction levels.

```
xtemp <- xtemp[, !sel, drop = FALSE]
xbar <- xbar[!sel]
```
but this creates its own problem in that stan is fitting to a rank deficient matrix and will return a coefficient for the empty interaction level.

I think the correct solution probably involves dropping the empty interaction column for fitting, but having variable in the stanreg object and giving it an NA values for everything.

**Comment by jgabry** [comment]
Sorry it took so long to get to this! Should be fixed by PR #522.

**Comment by lrmcdonald** [comment]
I have updated rstanarm to the development version on github hoping this was merged and fixed, but I still receive this same error using rstanarm::stan_clogit with loo.

Error in stanmat[, beta_sel, drop = FALSE]: subscript out of bounds.

version info:
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie 

rstan: 2.21.7
rstanarm: 2.21.3
