### ISSUE TITLE
stan_glmer messed up after recent merge

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#43]
@bgoodri I'm not sure what's going but after your recent merge for the `posterior_predict` stuff this example

    stan_lmer(Reaction ~ Days + (Days | Subject), data = sleep study)

throws an error. It has something to do with the `_NEW_` terms. We're getting `b[(Intercept) Subject:_NEW_Subject]` but missing the `_NEW_` term for `Days`.

**Comment by bgoodri** [comment]
Yeah the merge was really messy with a lot of conflicts. I think this
particular one I have fixed locally.

**Comment by bgoodri** [comment]
I think this was fixed by 23dd5558e5eee31f12a8e1f9d1be9279b830ae88

**Comment by jgabry** [comment]
@bgoodri Cool. Looks ok. 

It looks like some of the `posterior_predict` tests for stan_(g)lmer are still failing though. In particular there's an error being thrown about incorrect dimensions in some cases. For example, for 

    fit <- stan_lmer(mpg ~ wt + (1|cyl) + (1 + wt|gear), data = mtcars)

the last two `expect_silent()`s in the `check_for_error()` function in `test_posterior_predict.R` fail. The first is

    yrep5 <- posterior_predict(fit, newdata = model.frame(fit)[1:5, ])

    Error in b %*% dat$Zt : 
      Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90

So it looks like the error is being thrown by some C code for sparse matrix stuff that gets called for `b %*% dat$Zt`.

**Comment by bgoodri** [comment]
OK, I fixed all those. The remaining two test failures are

  2. Failure (at test_stan_glmer.R#42): stan_lmer returns expected result
for slepstudy example
  3. Failure (at test_stan_glmer.R#99): stan_glmer.nb ok

which seem to just be that we get sufficiently different answers than lme4.
But I don't think anything was supposed to have changed with the
estimation. Were these working before?

**Comment by jgabry** [comment]
Hmm, yeah I'm pretty sure they were working before. At least the travis
build succeeded a few times after they were introduced. Maybe they're just
really sensitive to the seed for the rngs called from posterior_predict? I
think we've only been setting seeds for the calls to Stan (although I did
add a seed argument to posterior_predict).

**Comment by bgoodri** [comment]
OK. I'll investigate that more later. Is there any progress on the ggplot2
thing? We really need to get a new rstan and a rstanarm onto CRAN by the
first week of January.

**Comment by jgabry** [comment]
The vignette that was throwing the ggplot2 error for you builds fine for
me. Was it failing on travis or just for you locally?

**Comment by bgoodri** [comment]
On Dec 29, 2015 6:42 PM, "Jonah Gabry" <notifications@github.com> wrote:

> The vignette that was throwing the ggplot2 error for you builds fine for
> me. Was it failing on travis or just for you locally?
>

I can't reproduce it now either, but I don't know what fixed it.

**Comment by jgabry** [comment]
Ok, that's good, but weird.

Also, I realized that those tests you said were still failing weren't for
posterior_predict but just stan_glmer, so I was probably wrong about it
just being sensitivity to the seed (since we have been setting the seed
passed to Stan for those examples).
