### ISSUE TITLE
ignoring priors?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#48]
From @waynefoltaERI (via [brms issue 24](https://github.com/paul-buerkner/brms/issues/24))

>For example, while playing with the mtcars dataset for this issue, I found that brms' and rstanarm's answers differed considerably. And glm agreed with rstanarm... which gave me a clue and when I investigated further, it appears that rstanarm is ignoring priors. (Or I am misunderstanding how they are specified, but not getting any error messages.) So the reason for the agreement is that I was specifying priors, but rstanarm was ignoring them and using flat (improper, frequentist-like) priors. Maybe has to do with their pre-compilation.

**Comment by jgabry** [comment]
@waynefoltaERI 

Can you share the example you were using? I don't think rstanarm is ignoring priors. For example:

    fit <- stan_glm(mpg ~ wt, data = mtcars, prior = normal(0, 5), prior_intercept = normal(0, 10))

 gives pretty similar results to `glm(mpg ~ wt, data = mtcars)`. However, if I make the priors ridiculous just as a test 

    fit2 <- stan_glm(mpg ~ wt, data = mtcars, prior = normal(-100, 1), prior_intercept = normal(100, 1))

then the estimates are horrible because they are seriously affected by the priors.

**Comment by paul-buerkner** [comment]
It might be a problem in `brms` (not in `rstanarm`) when using fixed effects only. I am currently investigating this.

**Comment by jgabry** [comment]
Ok, thanks Paul.

**Comment by waynefoltaERI** [comment]
Instead of `normal (-100, 1)`, try `normal (0, 0.3)` for both. I get basically the same results as I do for `normal (0, 10)`, which is basically the same results as `glm`. I hadn't reported this as an issue here, but only mentioned it at the `brms` issues because I hadn't had time to think through the issues. My first thought was that a super-narrow prior with not much data should affect the CI's of the estimates, but I'm not so sure that's correct.

**Comment by jgabry** [comment]
With this particular dataset, despite not having many observations, you need to go even tighter than that. If you try 0.03 instead of 0.3 and you should see a big difference.

**Comment by jgabry** [comment]
@waynefoltaERI You also mentioned in the brms issue that there were some other issues with rstanarm that you noticed. We fixed a lot of things before submitting to CRAN but if you're still finding those issues it would be really helpful to know what they are if you don't mind sharing.

**Comment by waynefoltaERI** [comment]
Let me gather my notes. The things that immediately come to mind are various `stan_` plots not working, on the results of logistic regressions, etc. Some of it may boil down to `ggplot2`, Stan 2.9, `rstan`, et al, having new releases at the same time and not being totally compatible. I've been focusing on `brms` for a blog posting I'm working on and `rstanarm` was a last-minute find, so I'm not as organized on that side of things.

**Comment by waynefoltaERI** [comment]
OK, that was the kind of issue that I hadn't been able to work through, but caused me to hesitate to report it as a issue here yet.

In terms of something more concrete, the last three plots fail:

```R
rstan_options (auto_write=TRUE)
options (mc.cores=parallel::detectCores ())

set.seed (3875)

ir <- data.frame (scale (iris[, -5]), Species=iris[, 5])

ir2 <- iris[-c(1:50),]
ir2$Species <- factor (ir2$Species)

library (rstanarm)
library (rstan)
library (shinystan)

br2 <- stan_glm (Species ~ Petal.Length + Petal.Width + Sepal.Length + Sepal.Width, data=ir2,
                              family=binomial (link="logit"), chains=3, iter=3000, warmup=600,
                              prior=normal (0, 5), prior_intercept=normal (0, 5))

stan_diag (br2, information="sample")  # Error due to warmup samples?
pp_check (br2, check="reside")
launch_shinystan (br2)   
```

**Comment by jgabry** [comment]
Thanks for sharing. Several issues here:

The issue with the stan_diag plot is something that needs to be dealt with
in rstan. Thanks for pointing it out.

The other two issues are really the same issue and are occurring because of
an error in the binned residuals plot (which is now fixed in the latest
commit). If you don't want to reinstall, then a temporary solution is to
use

I(Species == "versicolor")

as the left hand side of the formula (instead of just Species), in which
case pp_check and launch_shinystan should work fine. After reinstalling
from GitHub your original version should work too.

**Comment by waynefoltaERI** [comment]
Great, I"m installing from github now. (The installation does generate four parser warnings:

```Left-hand side of sampling statement (~) may contain a non-linear transform of a parameter or local variable.
If so...```

In case that is new. I'll continue to poke through my examples to find anything else I can report here.

Thanks!

**Comment by waynefoltaERI** [comment]
Followup, the github version does fix the `pp_check` plot, which I was most excited about.

But there is another `launch_shinystan` error:

```
Error in Summary.factor(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  : 
  ‘min’ not meaningful for factors
```

**Comment by jgabry** [comment]
Thanks a lot. A few updates:

1) The develop branch of rstan should also now have the fix for the issue
with stan_diag.

2) You can ignore those parser warnings. They're just false positives
issued by the Stan parser (I think they're only visible when installing
through GitHub and not CRAN).

3) That launch_shinystan error actually also has to do with pp_check, but
it should be fixed now.

Thanks again. This is a brand new package, so we're definitely still
working out some kinks. Feedback like this is really helpful.

**Comment by jgabry** [comment]
Regarding the plots needing `library(rstan)` first, that's not quite true, you just need to call them using the plot method included with rstanarm (or you can do what you did and first load rstan and then call the plotting functions directly). If you use the plot method in rstanarm then you can call the various plotting functions without having to first use library(rstan), e.g.:

    library(rstanarm)
    fit <- stan_glm(mpg ~ wt, data = mtcars)
    plot(fit, "trace") # calls stan_trace

The help page for `plot.stanreg` has more details and examples.

All of rstanarm should work without having to call `library(rstan)`. rstanarm has rstan in Imports rather than Depends (in the package description), which prevents some namespace clutter and various other annoyances and I think ends up being a virtue.

**Comment by jgabry** [comment]
I'm going to close this issue for now as I think everything discussed here is now fixed, but please feel free to continue commenting here if you have any other questions/suggestions, or to open new issues if you find anything else. Thanks again for your help.

**Comment by waynefoltaERI** [comment]
OK, just to clarify, the version obtained by `devtools::install_github("stan-dev/rstanarm", args = "--preclean")` is not the development version, so the issues are not fixed in it, correct? What would be the `install_github` to get the development version?

(As I mentioned, only some of the `pp_check` options work in the version I just downloaded with this command, so I just want to make sure we're on the same page.)

Also, and probably underlying some of the issues, the following fails:

```R
rstan_options (auto_write=TRUE)
options (mc.cores=parallel::detectCores ())

set.seed (3875)

ir <- data.frame (scale (iris[, -5]), Species=iris[, 5])

ir2 <- iris[-c(1:50),]
ir2$Species <- factor (ir2$Species)

library (rstanarm)  # Overrides cauchy, fixef, ngrps, ranef, and VarCorr from package brms!!
library (rstan)

system.time (br2 <- stan_glm (Species ~ Petal.Length + Petal.Width + Sepal.Length + Sepal.Width, data=ir2,
                              family=binomial (link="logit"), chains=3, iter=3000, warmup=600,
                              prior=normal (0, 5), prior_intercept=normal (0, 5)))

y_rep <- posterior_predict (br2)
```
All predictions are NA.

**Comment by jgabry** [comment]
That's weird. Can you try that same `install_github` command again and see if it works? I think we might just have gotten a bit out of sync with the timing of the issue comments and my commits (which may have taken a while to upload for some reason). Sorry about that. 

`posterior_predict` should be working properly too if installation works this time.

**Comment by waynefoltaERI** [comment]
OK, you're evidently right about the out-of-sync, it all works for me now (7:53 pm EST).

**Comment by jgabry** [comment]
Ok thanks, glad that's working. And thanks again for reporting those errors.

**Comment by jgabry** [comment]
I was going back through the thread and noticed a few other tidbits I meant to mention. In no particular order:

* The model you're using in your example will actually converge with `iter = 200`, so you definitely don't need `iter=3000, warmup=600` (it doesn't hurt, it's just unnecessary). With rstanarm I've rarely needed more than the default of `iter=2000, warmup=1000` and models you can fit with rstanarm will converge in way fewer iterations than that.
 
* It won't hurt anything if you keep it, but because of how rstanarm works you don't need to set `rstan_options(auto_write = TRUE)`. One less thing to worry about remembering. 

* That all those functions (e.g. fixef, ngrps, ranef, etc) are masked from brms when loading rstanarm isn't unique to rstanarm. The same thing will happen in reverse if you load the packages in the opposite order.  It's because in addition to defining S3 methods for brmsfit and stanreg objects both packages have to export the S3 generic as well.

* Using `pp_check(..., check = "test", test = "mean")` is definitely useful for logistic regression because it's checking the distribution of Pr(yrep = 1|y). I agree that using `test="scatter"` isn't particularly useful for logistic regression.

Hope thats helpful
